import Header from "@/components/header/Header";
import type { Metadata } from "next";
import { Questrial, Syne } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const questrial = Questrial({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-questrial",
  weight: "400",
});

const syne = Syne({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-syne",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${questrial.variable} ${syne.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
